version: '1'
services:
  pubsub-emulator:
    image: google/cloud-sdk:latest
    ports:
      - "8085:8085"
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--project=your-project-id", "--host-port=0.0.0.0:8085"]
