version: '1'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    network_mode: service:pubsub-emulator
    command: sleep infinity
    volumes:
      - ..:/workspace:cached

  pubsub-emulator:
    image: google/cloud-sdk:latest
    ports:
      - "8085:8085"
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--project=your-project-id", "--host-port=0.0.0.0:8085"]